config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

   root 'collections#index'

   resources :collections

   resources :authors

   resources :photos

end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :photos
end

app/models/collection.rb
class Collection < ActiveRecord::Base
  has_many :photos
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :collection
  belongs_to :author
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  def index
    @collections = Collection.order('title ASC')
  end

  def show
    @collection = Collection.find(params[:id])
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    @photos = Photo.where(:collection_id => :id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/collections/index.html.erb
<div class="logo">
  <%= image_tag 'source/logo.jpg', :class => 'logo'%>
</div>

<% @collections.each do |c| %>
  <div class="collection">
    <div class="title">
      <h2><%= link_to c.title, collection_path(c) %></h2>
      <p><%= c.description %></p>
    </div>
    <div class="thumbnails">
      <% c.photos.each do |p| %>
      <% if p.main_thumbnail == true %>
      <div class="main-thumbnail">
        <%= p.title %>
        <%= image_tag p.image_url, :class => 'responsive-image' %>
      </div>
      <% end %>
      <% if p.special_thumbnail == true %>
      <div class="special-thumbnail">
        <%= image_tag p.image_url, :class => 'responsive-image' %>
      </div>
      <% end %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/collections/show.html.erb
<div class="photo-container">
  <h1><%= @collection.title %></h1>
  <div class="gallery">
    <ul>
      <!-- TODO: sostituire all'id il counter del loop altrimenti non funziona con le altre gallerie -->
      <% @collection.photos.each_with_index do |p, i| %>
      <li><%= image_tag p.image_url, :class => 'responsive-image photo', :id => i %></li>
      <% end %>
    </ul>
  </div>

  <div class="gallery-thumbnail">
    <ul>
      <% @collection.photos.each_with_index do |p, i| %>
      <li><%= image_tag p.image_url, :class => 'responsive-image thumbs', :id => i %></li>
      <% end %>
    </ul>
  </div>

  <div class="info">
    <% @collection.photos.each_with_index do |p, i| %>
    <div class="photo-info" id="<%= p.id %>">
    <h1><%= p.title %></h1>
    <p><%= p.description %></p>
    </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DentoApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
</head>
<body>

  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'GC', root_path, :class => 'navbar-brand' %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="active"><%= link_to 'home', root_path %></li>
          <li><a href="curriculum.html">Curriculum</a></li>
          <li><a href="contatti.html">Contatti</a></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

<div class="main">
  <%= yield %>
</div>

</body>
</html>